exampleauth-authpage:
    path:       /authpage
    defaults:   { _controller: 'SimpleSAML\Module\exampleauth\Controller\ExampleAuth::authpage' }
exampleauth-redirect:
    path:       /redirect
    defaults:   { _controller: 'SimpleSAML\Module\exampleauth\Controller\ExampleAuth::redirect' }
exampleauth-resume:
    path:       /resume
    defaults:   { _controller: 'SimpleSAML\Module\exampleauth\Controller\ExampleAuth::resume' }
